# services:
#   - type: web
#     name: quantum-simulator
#     env: node
#     buildCommand: npm install && cd frontend-interface && npx next build 
#     startCommand: cd frontend-interface && npx next start -p $PORT
#     envVars:
#       - key: PORT
#         value: "10000"