name: Code Coverage Summary

on:
  push:
    branches:
      - '**'  # Runs on all branches

jobs:
  coverage-summary:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.20'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        cd backend
        PYTHONPATH=${{ github.workspace }}/backend pytest --cov=./ --cov-report=term-missing:skip-covered --cov-report=xml --cov-report=html
      env:
        PYTHONPATH: ${{ github.workspace }}/backend
        
    - name: Move coverage reports
      run: |
        mv backend/coverage.xml ./coverage.xml
        mv backend/htmlcov ./htmlcov

    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        format: markdown
        output: both
        thresholds: '60 80'

    - name: Upload Detailed Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-details
        path: htmlcov/
        retention-days: 14