name: Code Coverage Summary

on:
  push:
    branches:
      - '**'  # Runs on all branches

jobs:
  coverage-summary:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.20'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        cd backend
        PYTHONPATH=${{ github.workspace }}/backend pytest --cov=./ --cov-report=xml --cov-report=term
      env:
        PYTHONPATH: ${{ github.workspace }}/backend
        
    - name: Move coverage report
      run: |
        mv backend/coverage.xml ./coverage.xml
        
    - name: Code Coverage Summary
      id: coverage
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        format: markdown
        output: both
        thresholds: '60 80'

    - name: Output Coverage Summary
      run: |
        echo "### Coverage Summary Report" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md